### ISSUE TITLE
coding

### ISSUE THREAD

**Issue by Buburry** [Buburry/Project_scrath_10#10]
![373067701_2540996082728659_2687337776227274815_n](https://github.com/Buburry/Project_scrath_10/assets/141802154/84f67071-9835-4223-b7fb-e8bb6165a52d)
![371338808_318801077274111_5070188126463725336_n](https://github.com/Buburry/Project_scrath_10/assets/141802154/5929feac-3c1b-47ad-a671-8fa56b993590)

**Comment by Buburry** [comment]
[1 (2).zip](https://github.com/Buburry/Project_scrath_10/files/12525543/1.2.zip)

**Comment by Buburry** [comment]
มันมี bug อยู่ตรงตัวที่ 1(5) ลองลบก่อนก็ได้ กับตรงกระสุนคือ ตอนแรก เราจะลองทำผลัดทีละเวฟ เวฟแรกพุ่งชน เวฟหลังยิงกระสุนแต่ยังไม่เสร็จ

**Comment by PhuriphatYoosuwan** [comment]
มันเปิดในscratchไม่ได้อะ

**Comment by Buburry** [comment]
[ยาน ยิง และฉาก2 (2).zip](https://github.com/Buburry/Project_scrath_10/files/12525849/2.2.zip)

**Comment by Buburry** [comment]
ได้ปะ

**Comment by PhuriphatYoosuwan** [comment]
[ยาน-ยิง-และฉาก-v3.zip](https://github.com/Buburry/Project_scrath_10/files/12533951/-.-.-v3.zip)

**Comment by PhuriphatYoosuwan** [comment]
[ยิงฉากขยับอัปเกรดverล่าสุด.zip](https://github.com/Buburry/Project_scrath_10/files/12546927/ver.zip)

**Comment by PhuriphatYoosuwan** [comment]
[tinywow_zip_33889322.zip](https://github.com/Buburry/Project_scrath_10/files/12565386/tinywow_zip_33889322.zip)

**Comment by PhuriphatYoosuwan** [comment]
[เวฟเสดแล้วเหลือเกมโอเวอร์กับบอส.zip](https://github.com/Buburry/Project_scrath_10/files/12566657/default.zip)

**Comment by PhuriphatYoosuwan** [comment]
[tinywow_zip_34096602.zip](https://github.com/Buburry/Project_scrath_10/files/12577599/tinywow_zip_34096602.zip)

**Comment by Buburry** [comment]
[Untitled-11.zip](https://github.com/Buburry/Project_scrath_10/files/12577816/Untitled-11.zip)

**Comment by PhuriphatYoosuwan** [comment]
[บอสเสดแล้วน่าจะพอเทสได้ละมั้ง.zip](https://github.com/Buburry/Project_scrath_10/files/12580031/default.zip)

**Comment by PhuriphatYoosuwan** [comment]
[tinywow_zip_34196382.zip](https://github.com/Buburry/Project_scrath_10/files/12586900/tinywow_zip_34196382.zip)

**Comment by Buburry** [comment]
[Uploading ปุ่มเลือกด่าน (3).zip…]()
[Uploading formation wave 8 round.zip…]()
[Uploading bossdw.zip…]()

**Comment by Buburry** [comment]
start
mons ไม่ซ้ำกัน 8 wave
boss ลิง เหลือทำ HP

**Comment by PhuriphatYoosuwan** [comment]
[Uploading tinywow_zip_34238985.zip…]()

**Comment by PhuriphatYoosuwan** [comment]
[tinywow_zip_34238985.zip](https://github.com/Buburry/Project_scrath_10/files/12591379/tinywow_zip_34238985.zip)

**Comment by Buburry** [comment]
[bossdw (1).zip](https://github.com/Buburry/Project_scrath_10/files/12592970/bossdw.1.zip)
[Uploading ปุ่มเลือกด่าน (3).zip…]()
[formation wave 8 round.zip](https://github.com/Buburry/Project_scrath_10/files/12592974/formation.wave.8.round.zip)

**Comment by Buburry** [comment]
[ปุ่มเลือกด่าน (3).zip](https://github.com/Buburry/Project_scrath_10/files/12592973/3.zip)

**Comment by Buburry** [comment]
[left mon .zip](https://github.com/Buburry/Project_scrath_10/files/12593152/left.mon.zip)
[mons1 HP.zip](https://github.com/Buburry/Project_scrath_10/files/12593153/mons1.HP.zip)

**Comment by PhuriphatYoosuwan** [comment]
[AAAA.zip](https://github.com/Buburry/Project_scrath_10/files/12593522/AAAA.zip)

**Comment by PhuriphatYoosuwan** [comment]
[aaaa2.zip](https://github.com/Buburry/Project_scrath_10/files/12594114/aaaa2.zip)

**Comment by Buburry** [comment]
[bossdw (2).zip](https://github.com/Buburry/Project_scrath_10/files/12594149/bossdw.2.zip)

**Comment by PhuriphatYoosuwan** [comment]
[aaaa2.zip](https://github.com/Buburry/Project_scrath_10/files/12594269/aaaa2.zip)

**Comment by PhuriphatYoosuwan** [comment]
[aaaa3.zip](https://github.com/Buburry/Project_scrath_10/files/12594361/aaaa3.zip)

**Comment by Buburry** [comment]
[bossdw (2).zip](https://github.com/Buburry/Project_scrath_10/files/12594386/bossdw.2.zip)
[bossdw (3).zip](https://github.com/Buburry/Project_scrath_10/files/12594389/bossdw.3.zip)

**Comment by PhuriphatYoosuwan** [comment]
[aaaa5.zip](https://github.com/Buburry/Project_scrath_10/files/12594461/aaaa5.zip)

**Comment by PhuriphatYoosuwan** [comment]
[sound.zip](https://github.com/Buburry/Project_scrath_10/files/12594819/sound.zip)

**Comment by PhuriphatYoosuwan** [comment]
[qqqq4.zip](https://github.com/Buburry/Project_scrath_10/files/12594899/qqqq4.zip)

**Comment by PhuriphatYoosuwan** [comment]
[meteor.zip](https://github.com/Buburry/Project_scrath_10/files/12594918/meteor.zip)
