### ISSUE TITLE
Story : ฉากแรก 

### ISSUE THREAD

**Issue by Buburry** [Buburry/Project_scrath_10#13]
story ที่อธิบายเนื้อเรื่อง

**Comment by Apicha660612162** [comment]
![ฉากหลัง38](https://github.com/Buburry/Project_scrath_10/assets/141741376/27665444-1b22-4949-b0ac-e6f446fd7a98)
![ฉากหลัง33](https://github.com/Buburry/Project_scrath_10/assets/141741376/0b9dabf8-89c0-4379-822a-09e46188e033)
![ฉากหลัง31](https://github.com/Buburry/Project_scrath_10/assets/141741376/faa1bde7-0b4e-48d6-becd-169dcf5180de)

**Comment by Buburry** [comment]
เรียงยังไง
