### ISSUE TITLE
Design ยานอวกาศ ตัวละครที่เล่น

### ISSUE THREAD

**Issue by Buburry** [Buburry/Project_scrath_10#14]
เป็นยานอวกาศ

**Comment by Apicha660612162** [comment]
![8 (1)](https://github.com/Buburry/Project_scrath_10/assets/141741376/687593a3-0fb3-47b4-b373-22081cb3055f)
![f4213f110a8c2aa8](https://github.com/Buburry/Project_scrath_10/assets/141741376/bf3d2d0e-c8e8-4fb6-af2b-f9866801856b)
![c1a05aee737130f5](https://github.com/Buburry/Project_scrath_10/assets/141741376/5deaa204-3b20-453d-96dd-7a0c6b4bacfd)
![6d3290706e312631](https://github.com/Buburry/Project_scrath_10/assets/141741376/6c6b3f9a-b532-4d94-8e26-cf3c7c47e113)
![14 (1)](https://github.com/Buburry/Project_scrath_10/assets/141741376/3fee6e99-a711-49fe-b36f-d401be673c39)
![12 (1)](https://github.com/Buburry/Project_scrath_10/assets/141741376/26f6ada6-bc6e-4e7e-b226-92e130ca69b8)

**Comment by Apicha660612162** [comment]
![8 (2)](https://github.com/Buburry/Project_scrath_10/assets/141741376/789408a0-fec9-4a14-a8ad-f2539f36afc5)
![14 (1)](https://github.com/Buburry/Project_scrath_10/assets/141741376/e28b448d-6b1b-4c21-ac5a-fad16609616e)
![13](https://github.com/Buburry/Project_scrath_10/assets/141741376/f257f9fc-5ff1-47c7-86f2-ec1cf433b830)
![12 (1)](https://github.com/Buburry/Project_scrath_10/assets/141741376/e05c72be-7083-44e3-a99d-2ec00687b53e)
![10 (1)](https://github.com/Buburry/Project_scrath_10/assets/141741376/4df28f35-abc4-46a5-a9de-eb856e2cbdb9)
![9 (2)](https://github.com/Buburry/Project_scrath_10/assets/141741376/2fbbfc9e-0363-42d7-8dd6-a7bd41882604)
