### ISSUE TITLE
Design Adums

### ISSUE THREAD

**Issue by jjjaoant** [Buburry/Project_scrath_10#17]
ตัวละครหลัก (ตัวเอก)

**Comment by Buburry** [comment]
![1 3 (1)](https://github.com/Buburry/Project_scrath_10/assets/141802154/a2dd4dd5-ecfe-427e-9b79-cc08517fbd0e)

**Comment by Buburry** [comment]
![Uploading 1.2.svg…]()

**Comment by Buburry** [comment]
![1 1](https://github.com/Buburry/Project_scrath_10/assets/141802154/bf59245e-b0ed-4cc0-a6e2-13e822079f84)
