### ISSUE TITLE
Design ลูกกระจ๊อก 2

### ISSUE THREAD

**Issue by jjjaoant** [Buburry/Project_scrath_10#18]

**Comment by Buburry** [comment]
![Uploading 4 (2).svg…]()

**Comment by Buburry** [comment]
![Uploading 2 (3).svg…]()

**Comment by Buburry** [comment]
![3 (2)](https://github.com/Buburry/Project_scrath_10/assets/141802154/b4c70a77-3368-42c7-a4ca-534a83ec0d15)

**Comment by Buburry** [comment]
![1 (2)](https://github.com/Buburry/Project_scrath_10/assets/141802154/0ab7b523-f79a-4ae5-8d6d-984b301909f3)
