### ISSUE TITLE
Design ลูกกระจ๊อก 3

### ISSUE THREAD

**Issue by jjjaoant** [Buburry/Project_scrath_10#20]

**Comment by Buburry** [comment]
![1 (3)](https://github.com/Buburry/Project_scrath_10/assets/141802154/9e50dfed-b352-4184-921c-33152d7c2a77)

**Comment by Buburry** [comment]
![Uploading 2 (5).svg…]()

**Comment by Buburry** [comment]
![3 (3)](https://github.com/Buburry/Project_scrath_10/assets/141802154/542ec4f9-3929-4608-86e2-90611a00657d)

**Comment by Buburry** [comment]
![Uploading 4 (4).svg…]()
