### ISSUE TITLE
Design Boss 

### ISSUE THREAD

**Issue by jjjaoant** [Buburry/Project_scrath_10#25]

**Comment by Apicha660612162** [comment]
![17](https://github.com/Buburry/Project_scrath_10/assets/141741376/739ccffc-7220-49b8-a2ed-7fcff4ba2ae7)
![16](https://github.com/Buburry/Project_scrath_10/assets/141741376/87551501-5a0a-4e91-b72a-047e4c42ab77)
![4 (5)](https://github.com/Buburry/Project_scrath_10/assets/141741376/140ddf03-b0c5-4343-b367-89ac76d65cbd)
![2 (6)](https://github.com/Buburry/Project_scrath_10/assets/141741376/1dc2c6a6-d89e-45c5-b309-bd1a02a935e7)
![2_10](https://github.com/Buburry/Project_scrath_10/assets/141741376/df4cd819-cddd-41c7-80ba-533e6ad5bdb0)
![2_11](https://github.com/Buburry/Project_scrath_10/assets/141741376/dc8e913c-3a47-452b-987f-ac1b3a41f962)
![18](https://github.com/Buburry/Project_scrath_10/assets/141741376/797659e5-452c-470e-84e2-6cbe158bf928)
