### ISSUE TITLE
Design ลูกกระสุน 2

### ISSUE THREAD

**Issue by jjjaoant** [Buburry/Project_scrath_10#29]

**Comment by Buburry** [comment]
![c1a05aee737130f5](https://github.com/Buburry/Project_scrath_10/assets/141802154/6c367d2a-bb25-4226-81b8-d94d83a42fcd)

**Comment by Buburry** [comment]
![4](https://github.com/Buburry/Project_scrath_10/assets/141802154/61e2eb9a-ad8b-4ebc-afa5-010f8e7f4054)

**Comment by Buburry** [comment]
![3](https://github.com/Buburry/Project_scrath_10/assets/141802154/cca4165d-9a81-4a6a-896d-9a0f1702d99f)

**Comment by Buburry** [comment]
![Uploading 2 (1).svg…]()

**Comment by Buburry** [comment]
![1_1](https://github.com/Buburry/Project_scrath_10/assets/141802154/0209706e-1703-4b9c-8b8d-2f861819fa18)

**Comment by Buburry** [comment]
![88a8242db8f53ce8](https://github.com/Buburry/Project_scrath_10/assets/141802154/73c88cdd-aa54-4b7c-b7eb-096bc1a9e45f)
