### ISSUE TITLE
Design background 5 ด่าน 

### ISSUE THREAD

**Issue by jjjaoant** [Buburry/Project_scrath_10#34]
มีด่าน5ด่าน เเต่ล่ะด่านมีฉากหลังเเตกต่างกัน

**Comment by Apicha660612162** [comment]
![ฉาก1](https://github.com/Buburry/Project_scrath_10/assets/141741376/f7b36709-e759-435c-864e-1dbaa2046bbc)
![ฉาก2](https://github.com/Buburry/Project_scrath_10/assets/141741376/c7dc78ea-fc35-40fb-bcc3-7aeca73908d3)
![ฉาก3](https://github.com/Buburry/Project_scrath_10/assets/141741376/bea3c724-978b-4a9c-8b8c-f0c33d31c6e9)
![ฉาก4](https://github.com/Buburry/Project_scrath_10/assets/141741376/70a85e51-a1d9-423b-a63f-ab942b0bf3fb)
![ฉาก5](https://github.com/Buburry/Project_scrath_10/assets/141741376/3effd1b1-3d19-4980-8b3a-a7b7f7fe4c1c)
