### ISSUE TITLE
2. ด่าน 1 : การเคลื่อนที่

### ISSUE THREAD

**Issue by Buburry** [Buburry/Project_scrath_10#37]
การเคลื่อนไหวของยาน และการขยับเดินหน้าของฉาก

**Comment by PhuriphatYoosuwan** [comment]
[ยาน ยิง และฉาก.zip](https://github.com/Buburry/Project_scrath_10/files/12496037/default.zip)

**Comment by PhuriphatYoosuwan** [comment]
[ลูกกระจ๊อก.zip](https://github.com/Buburry/Project_scrath_10/files/12496566/default.zip)

**Comment by Buburry** [comment]
[Uploading ยาน ยิง และฉาก2 (1).zip…]()
