### ISSUE TITLE
2. ด่าน 1 : การเคลื่อนที่ของ ลูกกระจ๊อก 1

### ISSUE THREAD

**Issue by Buburry** [Buburry/Project_scrath_10#38]
หมวด 2
ด่านที่ 1
 การเคลื่อนที่ของ ลูกกระจ๊อก 1

**Comment by PhuriphatYoosuwan** [comment]
[ลูกกระจ๊อก.zip](https://github.com/Buburry/Project_scrath_10/files/12525418/default.zip)

**Comment by Buburry** [comment]
[Uploading ยาน ยิง และฉาก2 (1).zip…]()
