### ISSUE TITLE
3. ด่าน 2 : ลูกกระจ๊อก 2

### ISSUE THREAD

**Issue by Buburry** [Buburry/Project_scrath_10#46]
รูปแบบการเคลื่อนที่ใหม่ กับการโจมตีใหม่

**Comment by PhuriphatYoosuwan** [comment]
[ลูกกระจ๊อก.zip](https://github.com/Buburry/Project_scrath_10/files/12525420/default.zip)

**Comment by Buburry** [comment]
[Uploading formation wave 8 round.zip…]()
