### ISSUE TITLE
Design ตัวละคร เเละ ฉาก 

### ISSUE THREAD

**Issue by jjjaoant** [Buburry/Project_scrath_10#48]
ต้อง design ตัวละคร ฉาก รวมถึงภาพดีเทลต่างๆให้เสร็จเรียบร้อย

**Comment by Apicha660612162** [comment]
desige ตัวละคร
 - ตัวละครผู้เล่น+ลูกกระสุน
 - ลูกน้องboss 3 ตัวละคร+กระสุน
 - minibos1-4 +กระสุน
 - item drop เวลาที่bossตาย  1 ยิงไว 2 เพิ่มดาเมจให้กับตัวละครผู้เล่น 3 เพิ่มยิงไว x2
 - boss +กระสุน

-Extra อาจมีการเพิ่มดีเทล หลังจากการลองโค๊ดเสร็จสมบูรณ์

**Comment by Apicha660612162** [comment]
desige  black groud 
ยังไม่เสร็จ สมบูรณ์ มีฉากทดลอง3 ฉาก

**Comment by Apicha660612162** [comment]
story เล่าเรื่อง เริ่ม จบ 
ยังสรุปconcept ไม่ได้

**Comment by Apicha660612162** [comment]
![b2aa7969d1a245cdc647dd97f4b11f12](https://github.com/Buburry/Project_scrath_10/assets/141741376/b87a9cc9-5d47-42db-9f75-e3869274db79)
