### ISSUE TITLE
ฉากเพิ่มเติม

### ISSUE THREAD

**Issue by Apicha660612162** [Buburry/Project_scrath_10#66]

**Comment by Apicha660612162** [comment]
![คอสตูม4](https://github.com/Buburry/Project_scrath_10/assets/141741376/5adb32f1-d6a0-446f-b7a3-d1222dab0441)
![ฉากหลัง18](https://github.com/Buburry/Project_scrath_10/assets/141741376/d9794871-83cd-4fbd-8c69-2cd2f25010d6)
![ฉากหลัง17](https://github.com/Buburry/Project_scrath_10/assets/141741376/bc2c39b1-b52e-42c8-8c6e-b6edcf0129c2)
![ฉากหลัง16](https://github.com/Buburry/Project_scrath_10/assets/141741376/0264549f-72d8-48da-8dc2-fe7921c02253)
![ฉากหลัง15](https://github.com/Buburry/Project_scrath_10/assets/141741376/a58cb900-4712-4c10-ab7b-d5532802701d)
![ฉากหลัง14](https://github.com/Buburry/Project_scrath_10/assets/141741376/4aec07bb-5c97-4b6f-a7e3-10b8ae73786d)
![ฉากหลัง13](https://github.com/Buburry/Project_scrath_10/assets/141741376/4fd3f68f-3560-421e-9d96-e7ea0bac8e89)
![ฉากหลัง12](https://github.com/Buburry/Project_scrath_10/assets/141741376/00bd5b46-2946-4bf8-937d-5ef461e12277)
![ฉากหลัง11](https://github.com/Buburry/Project_scrath_10/assets/141741376/3e27d980-8f39-496c-99d4-47727dd6114e)
![ฉากหลัง10](https://github.com/Buburry/Project_scrath_10/assets/141741376/1b480775-46b6-42e3-9fc4-89db189cd662)
![คอสตูม1](https://github.com/Buburry/Project_scrath_10/assets/141741376/8322143d-8e1e-4124-80e2-b3730c122295)
![คอสตูม2](https://github.com/Buburry/Project_scrath_10/assets/141741376/202f7f50-ccca-4898-9194-6318b4a43814)
![คอสตูม3](https://github.com/Buburry/Project_scrath_10/assets/141741376/5c5d6673-e17c-455e-b58e-420412fae4e2)

**Comment by Apicha660612162** [comment]
![คอสตูม1 (1)](https://github.com/Buburry/Project_scrath_10/assets/141741376/4e93c8cd-0b9e-4bc6-b5fd-9e78e4bed746)

**Comment by Apicha660612162** [comment]
![คอสตูม5](https://github.com/Buburry/Project_scrath_10/assets/141741376/78795c52-1209-427f-8632-ca4a96910419)
![คอสตูม6](https://github.com/Buburry/Project_scrath_10/assets/141741376/666fc64e-349b-40f0-95b2-61ed13b65fc6)
![คอสตูม7](https://github.com/Buburry/Project_scrath_10/assets/141741376/37ed4f49-f91b-490e-8f74-bdbd73646725)
![คอสตูม8](https://github.com/Buburry/Project_scrath_10/assets/141741376/15643b0e-6ef0-464e-95a2-2f5d10c4c392)
![คอสตูม9](https://github.com/Buburry/Project_scrath_10/assets/141741376/9e8f2e70-9106-46d0-baeb-5af152fa3536)
![คอสตูม10 (1)](https://github.com/Buburry/Project_scrath_10/assets/141741376/0cc774f1-a0bf-435b-abf5-e726f6b0c3d6)
![คอสตูม11](https://github.com/Buburry/Project_scrath_10/assets/141741376/20e6db96-8db0-4c28-a2e7-5c2abede44af)

**Comment by Apicha660612162** [comment]
ปุ่มบังคับ
![e75bffc02c85bf4162e1f5bb8d5e7c7e](https://github.com/Buburry/Project_scrath_10/assets/141741376/54f861a0-c2d3-409c-9e07-81679501dfd5)

**Comment by Apicha660612162** [comment]
![e75bffc02c85bf4162e1f5bb8d5e7c7e4](https://github.com/Buburry/Project_scrath_10/assets/141741376/36614f5c-5e45-45a0-a9b2-0a72060994bc)


ปุ่มบังคับ

**Comment by Apicha660612162** [comment]
![e75bffc02c85bf4162e1f5bb8d5e7c7e4 (1)](https://github.com/Buburry/Project_scrath_10/assets/141741376/15a2dc2f-6441-4519-8ca3-4a26ed97b4d1)

แก้ปุ่ม

**Comment by Apicha660612162** [comment]
![สกรีนช็อต 2023-09-27 142048](https://github.com/Buburry/Project_scrath_10/assets/141741376/e2ff709d-4bb8-483f-96a6-9e696f503113)

**Comment by Apicha660612162** [comment]
![สกรีนช็อต 2023-09-27 143102](https://github.com/Buburry/Project_scrath_10/assets/141741376/f25fca52-fddf-4da7-969c-5e42724b1d68)
![Uploading สกรีนช็อต 2023-09-27 143038.png…]()

**Comment by Apicha660612162** [comment]
![สกรีนช็อต 2023-09-27 143102](https://github.com/Buburry/Project_scrath_10/assets/141741376/4cdab7c6-ff9a-4ccf-91b3-c8af7fd5c9be)

**Comment by Apicha660612162** [comment]
![สกรีนช็อต 2023-09-27 143038](https://github.com/Buburry/Project_scrath_10/assets/141741376/05e10932-24cb-444f-91e4-23ff296b1efa)

**Comment by PhuriphatYoosuwan** [comment]
![itemdrop](https://github.com/Buburry/Project_scrath_10/assets/141811087/29390d8d-c58f-4b37-9d0d-43cb162a2280)

**Comment by PhuriphatYoosuwan** [comment]
![q](https://github.com/Buburry/Project_scrath_10/assets/141811087/6197905d-5f8c-4feb-b8b0-e95897b6168b)

**Comment by PhuriphatYoosuwan** [comment]
![spacebar](https://github.com/Buburry/Project_scrath_10/assets/141811087/a3aafad2-7e94-4fc0-9b7e-6ae4d6f0a869)

**Comment by jjjaoant** [comment]
![S__37109780](https://github.com/Buburry/Project_scrath_10/assets/141805193/970017c0-eb9b-4a09-8751-61acc880df49)
